FROM node:22-alpine

WORKDIR /app

RUN corepack enable

COPY package.json yarn.lock .yarnrc.yml tsconfig.json ./
COPY .yarn ./.yarn
COPY apps/api/package.json apps/api/package.json
COPY apps/front/package.json apps/front/package.json
COPY packages/domain/package.json packages/domain/package.json
COPY packages/factory/package.json packages/factory/package.json

RUN yarn install --frozen-lockfile --network-timeout 60000

COPY packages packages

CMD ["yarn", "db:migrate"]
